### ISSUE TITLE
Several problems here...

### ISSUE THREAD

**Issue by lesliesage** [learn-co-curriculum/fewpjs-oo-reviewing-javascript-inheritance-quiz#1]
The first example block of code doesn't show up in Chrome through learn.co (though I can see it in the readme in GitHub). 

Also, rabbit.eats() would not return “[Name] is eating!”
- It doesn't inherit from Animal. 
- It inherits from Mammal, which does not have the eats method. 
- Not sure what we're supposed to assume is in the //... of the class definition. 

Also, question 3 and 5 are duplicates.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
