### ISSUE TITLE
Typo in code for Question 3

### ISSUE THREAD

**Issue by jrodden1** [learn-co-curriculum/fewpjs-oo-reviewing-javascript-inheritance-quiz#2]
While working out the answer for Question 3, I noticed an issue on line 9 in the code block.  I went ahead and answered the question and got the correct answer to question 3:  `super(name);`.  

For this answer to work with the given codeblock in question 3, though, line 9 should read `class Rabbit extends Animal` **not** `extends Mammal`. 

(The Mammal class doesn't exist in that code block)

**Comment by sgharms** [comment]
You're right! Updating.
